### ISSUE TITLE
Pre-requisites: ARM Template throwing error

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Implementing-Windows-Virtual-Desktop-in-the-enterprise#1]
[Before Hands-on-Lab: Task 2: ](https://github.com/microsoft/MCW-Implementing-Windows-Virtual-Desktop-in-the-enterprise/blob/main/Hands-on%20lab/Before%20the%20HOL%20-%20Implementing%20Windows%20Virtual%20Desktop%20in%20the%20enterprise.md#task-2-deploying-the-arm-template) On deploying the template, it gives an error saying: **The template resource 'NSGs' at line '177' and column '5' is invalid. The nested deployment has api-version '2019-10-01', which is not supported in api-version '2016-09-01' used to deploy the template. Please use api-version '2017-05-10' or later to deploy the template. Or use an older api-version for the nested deployment in the template.**

Can you please provide me the **Asset Location** as from the template I'm not able to access it.

Also, can you please confirm how much time it take for [Task 3 in Exercise 4](https://github.com/microsoft/MCW-Implementing-Windows-Virtual-Desktop-in-the-enterprise/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Implementing%20Windows%20Virtual%20Desktop%20in%20the%20enterprise.md#task-3-prepare-wvd-image) to run because for me it's taking more than an hour and maybe it's stuck:

![image](https://user-images.githubusercontent.com/50323628/92587566-768a5100-f2b5-11ea-933b-e879c900debb.png)

Can you please have a look into both issues.

Thanks,
Seerat Arora

**Comment by dwnatwick** [comment]
Seerat.  The issue on the Before HOL template deployment appears to be an issue on your Azure subscription.  I am not having any issue or any errors being thrown during deployment.  And, yes, the preparation of the golden image could take a while.  An hour does not seem out of the ordinary.  Thank you.  Dwayne

**Comment by dwnatwick** [comment]
I have tested this lab exercise without issue.  The assumption is that there is a policy in the user's environment that is blocking this template from running properly.

**Comment by SeeratArora** [comment]
Hi,
I retested the lab and this time it was smooth for me.
