### ISSUE TITLE
Content Update Required

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Implementing-Windows-Virtual-Desktop-in-the-enterprise#2]
Hi,

The following content needs to be updated. Please have a look into this.

- [Exercise 3: Task 3:](https://github.com/microsoft/MCW-Implementing-Windows-Virtual-Desktop-in-the-enterprise/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Implementing%20Windows%20Virtual%20Desktop%20in%20the%20enterprise.md#task-3-enable-ad-authentication-for-your-storage-account) Step 1: In Setup. Link Address provided does not have **' : '** after https as shown in the screenshot below. It should be - https://github.com/Azure-Samples/azure-files-samples/releases

![image](https://user-images.githubusercontent.com/50323628/93796540-9d9f3600-fc58-11ea-871d-57ae844b45a7.png)

- [Exercise 3: Task 4:](https://github.com/microsoft/MCW-Implementing-Windows-Virtual-Desktop-in-the-enterprise/blob/main/Hands-on%20lab/HOL%20step-by-step%20-%20Implementing%20Windows%20Virtual%20Desktop%20in%20the%20enterprise.md#task-4-configure-share-permissions) Step 15: Screenshot given for other two roles is incorrect.

![image](https://user-images.githubusercontent.com/50323628/93799371-b578b900-fc5c-11ea-81fd-c3a60bed2a78.png)

Thanks.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with latest author push.
