### ISSUE TITLE
List of issues with the instructions. 

### ISSUE THREAD

**Issue by hope77777** [microsoft/MCW-Implementing-Windows-Virtual-Desktop-in-the-enterprise#3]
**Before HOL**: 

Deploying the Azure Infrastructure to AD DS, **Task 2 Step 6**:  
**Purchase** is no longer used in Azure. It should direct users to **Review + Create** and then **Create**. 

**HOL Step by step Guide**

**Ex 2 Task 2 Step 5 and 6**: There is no list of users to add. 

**Ex 3 Task 3 Setup** : "From a Domain Joined Computer" (Assuming this means the DC VM that was created in the Deploying Azure Infrastructure to AD DS section). 
Need to clarify where this step needs to be completed from. 
Also the prerequisites indicate a synced account required with specific permissions.
Need instructions on how to add the Global Admin role to the WVD  Admin account that was setup during the Azure AD Sync exercise.

**Ex 3 Task 4 Step 13** (Minor) Screenshot is old Azure interface. portal has changed. 

**Ex 3 Task 5 Step 3** Screenshot is from File Share Properties.

**Ex 3 Task 5 Step 10** List of Permissions should be included. 

**Ex 4 Task 5 Step 6** Must add instructions to choose NO on share image to share image. (Otherwise you must create a gallery).

**Ex 6 Task 1 Step 5** Instructions are incorrect regarding using the image created earlier. Instructions at the end of Ex 4 indicate you will be using the sysprepped image you created however it is unclear in this step. Setting the number of VMs to 2 to remain under quota limit for Azure pass. 

**Ex 6 Task 3** The order of tabs is backwards for Application Group. Applications appears after Basics, then Assignments

**Comment by DawnmarieDesJardins** [comment]
@hope77777 
Hi Hans, thank you for bringing these to our attention.  We have scheduled a test/fix for this workshop where we can address your comments.  This will be complete and merged by the end of this month.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #4
